// Generated by https://quicktype.io

export interface Configurations {
    content: Content[];
    pageable: Pageable;
    totalPages: number;
    totalElements: number;
    last: boolean;
    size: number;
    number: number;
    sort: Sort;
    first: boolean;
    numberOfElements: number;
    empty: boolean;
}

export interface Content {
    id: number;
    name: string;
    createdAt: number;
    archived: boolean;
    certaintyLevel: number;
    loginAllStocks: number;
    loginOwnedStocks: number;
    loginUserOrders: number;
    loginMakeOrder: number;
    allStocksMakeOrder: number;
    allStocksEnd: number;
    ownedStocksMakeOrder: number;
    ownedStocksEnd: number;
    userOrdersMakeOrder: number;
    userOrdersEnd: number;
    userOrderDeleteOrder: number;
    makeOrderBuyOrder: number;
    makeOrderSellOrder: number;
    noOfOperations: number;
    noOfMoney: number;
}

export interface Pageable {
    sort: Sort;
    offset: number;
    pageNumber: number;
    pageSize: number;
    paged: boolean;
    unpaged: boolean;
}

export interface Sort {
    sorted: boolean;
    unsorted: boolean;
    empty: boolean;
}
