// Generated by https://quicktype.io

export interface Users {
  content: Content[];
  pageable: Pageable;
  last: boolean;
  totalPages: number;
  totalElements: number;
  size: number;
  number: number;
  sort: Sort;
  first: boolean;
  numberOfElements: number;
  empty: boolean;
}

export interface Content {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  role: Role;
  money: number;
  tag: Tag;
  isActive: boolean;
}

export enum Role {
  User = 'USER',
}

export enum Tag {
  Benchmark = 'BENCHMARK',
  Default = 'DEFAULT',
}

export interface Pageable {
  sort: Sort;
  offset: number;
  pageNumber: number;
  pageSize: number;
  unpaged: boolean;
  paged: boolean;
}

export interface Sort {
  sorted: boolean;
  unsorted: boolean;
  empty: boolean;
}
